
server.port: 8082
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/video-game-online-shop
    username: video-game-online-shop-admin
    password: video-game-online-shop-admin
